import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[shell]
program = "/usr/bin/nu"

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 8 }
opacity = 0.5
dynamic_title = false

[font]
size = 12.0

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[cursor]
unfocused_hollow = false

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ key = "A", mods = "Control|Shift", action = "SpawnNewInstance" }]
