use_nerdfont = true

[theme]
background = "default"
primary = "#cdd6f4"
secondary = "#cba6f7"
title = "#cba6f7"
playing = "#f9e2af"
playing_selected = "#f5e0dc"
playing_bg = "default"
highlight = "#11111b"
highlight_bg = "#f38ba8"
error = "black"
error_bg = "#f38ba8"
statusbar = "#f9e2af"
statusbar_progress = "#94e2d5"
statusbar_bg = "default"
cmdline = "#cdd6f4"
cmdline_bg = "#11111b"
search_match = "#f5e0dc"

[keybindings]
"Ctrl+u" = "move up 5"
"Ctrl+d" = "move down 5"
