return {
  'nvimdev/dashboard-nvim',
  event = 'VimEnter',
  config = function()
    require('dashboard').setup {
      theme = 'doom',
      config = {
        header = {
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          ' ░░░    ░░ ░░░░░░░  ░░░░░░  ░░    ░░ ░░ ░░░    ░░░ ',
          ' ▒▒▒▒   ▒▒ ▒▒      ▒▒    ▒▒ ▒▒    ▒▒ ▒▒ ▒▒▒▒  ▒▒▒▒ ',
          ' ▒▒ ▒▒  ▒▒ ▒▒▒▒▒   ▒▒    ▒▒ ▒▒    ▒▒ ▒▒ ▒▒ ▒▒▒▒ ▒▒ ',
          ' ▓▓  ▓▓ ▓▓ ▓▓      ▓▓    ▓▓  ▓▓  ▓▓  ▓▓ ▓▓  ▓▓  ▓▓ ',
          ' ██   ████ ███████  ██████    ████   ██ ██      ██ ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
          '                                                   ',
        },
        center = {
          {
            icon = '',
            icon_hl = '@field',
            desc = '  New               ',
            desc_hl = '@field',
            key = 'a',
            key_hl = '@field',
            key_format = ' %s',
            action = 'enew',
          },
          {
            icon = '',
            icon_hl = '@field',
            desc = '  Find File',
            desc_hl = '@field',
            key = 'f',
            key_hl = '@field',
            key_format = ' %s',
            action = 'Telescope find_files',
          },
          {
            icon = '',
            icon_hl = '@field',
            desc = '  History',
            desc_hl = '@field',
            key = 'h',
            key_hl = '@field',
            key_format = ' %s',
            action = 'Telescope oldfiles',
          },
          {
            icon = '',
            icon_hl = '@field',
            desc = '  File Explorer',
            desc_hl = '@field',
            key = 'o',
            key_hl = '@field',
            key_format = ' %s',
            action = 'Oil',
          },
          {
            icon = '',
            icon_hl = '@field',
            desc = '  Update',
            desc_hl = '@field',
            key = 'u',
            key_hl = '@field',
            key_format = ' %s',
            action = 'Lazy update',
          },
          {
            icon = '',
            icon_hl = '@field',
            desc = '  Quit',
            desc_hl = '@field',
            key = 'q',
            key_hl = '@field',
            key_format = ' %s',
            action = 'quit',
          },
        },
        footer = {},
      },
    }
  end,
  dependencies = { { 'nvim-tree/nvim-web-devicons' } },
}
