# Sets user-defined palette
palette = "catppuccin_mocha"

[username]
disabled = true
style_user = "teal"
style_root = "maroon"
format = '[$user ]($style)'

[hostname]
ssh_symbol = ' '
format = '[$ssh_symbol$hostname]($style) in '
style = 'yellow'

[cmd_duration]
disabled = true
format = 'took [$duration]($style) '
style = 'yellow'

[character]
success_symbol = "[♥](pink) "
error_symbol = "[ ](red)"
vimcmd_replace_one_symbol = "[♥](pink) "
vimcmd_replace_symbol = "[♥](pink) "
vimcmd_symbol = "[♥](pink) "
vimcmd_visual_symbol = "[♥](pink) "

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
commands = [['clang', '--version'], ['cc', '--version'], ['gcc', '--version']]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 4
style = "bold lavender"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = "󰊢 "

[git_commit]
tag_symbol = "  "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Arch = " "

[package]
disabled = true
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
disabled = true

[xmake]
symbol = " "

[zig]
symbol = " "

# palette tables should be last in the config ⚓️
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
