# Sets user-defined palette
palette = "catppuccin_mocha"

[username]
style_user = "teal"
style_root = "maroon"
format = '[$user ]($style)'
disabled = true

[hostname]
ssh_symbol = ' '
format = '[$ssh_symbol$hostname]($style) in '
style = 'green'

[cmd_duration]
format = 'took [$duration]($style) '
style = 'yellow'
disabled = true

[character]
success_symbol = "[♥](pink) "
error_symbol = "[ ](red)"
vimcmd_replace_one_symbol = "[♥](pink) "
vimcmd_replace_symbol = "[♥](pink) "
vimcmd_symbol = "[♥](pink) "
vimcmd_visual_symbol = "[♥](pink) "

[package]
disabled = true

[directory]
truncation_length = 4
style = "bold lavender"

[c]
commands = [['clang', '--version'], ['cc', '--version'], ['gcc', '--version']]

# palette tables should be last in the config ⚓️
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
