# custom plugins

[[mgr.prepend_keymap]]
on = "<C-P>"
run = "plugin playground"

[[mgr.prepend_keymap]]
on = ["g", "j"]
run = "plugin last-jump"
desc = "Goto last jump"

[[mgr.prepend_keymap]]
on = ["m", "c"]
run = "linemode custom"
desc = "Linemode: custom"

# fr plugin

[[mgr.prepend_keymap]]
on = ["f", "g"]
run = "plugin fr rg"
desc = "fr rg"

# frank plugin

[[mgr.prepend_keymap]]
on = ["f", "r"]
run = "plugin frank 'content rg'"
desc = "rg search"

[[mgr.prepend_keymap]]
on = ["f", "a"]
run = "plugin frank 'content rga'"
desc = "rga search"

[[mgr.prepend_keymap]]
on = ["f", "d"]
run = "plugin frank name"
desc = "fd search (all)"

[[mgr.prepend_keymap]]
on = ["f", "D"]
run = "plugin frank 'name dir'"
desc = "fd search (dir)"

[[mgr.prepend_keymap]]
on = ["f", "f"]
run = "plugin frank 'name file'"
desc = "fd search (file)"

[[mgr.prepend_keymap]]
on = ["f", "c"]
run = "plugin frank 'name cwd'"
desc = "fd search (cwd)"

# nightly frank

[[mgr.prepend_keymap]]
on = ["n", "r"]
run = "plugin frank-nightly 'content rg'"
desc = "rg search"

[[mgr.prepend_keymap]]
on = ["n", "a"]
run = "plugin frank-nightly 'content rga'"
desc = "rga search"

[[mgr.prepend_keymap]]
on = ["n", "d"]
run = "plugin frank-nightly name"
desc = "fd search (all)"

[[mgr.prepend_keymap]]
on = ["n", "D"]
run = "plugin frank-nightly 'name dir'"
desc = "fd search (dir)"

[[mgr.prepend_keymap]]
on = ["n", "f"]
run = "plugin frank-nightly 'name file'"
desc = "fd search (file)"

[[mgr.prepend_keymap]]
on = ["n", "c"]
run = "plugin frank-nightly 'name cwd'"
desc = "fd search (cwd)"

# quality of life

[[mgr.prepend_keymap]]
on = ["R"]
run = "rename --empty=stem --cursor=start"
desc = "Easy rename"

# https://yazi-rs.github.io/docs/tips

[[mgr.prepend_keymap]]
on = "2"
run = "plugin switch-tab 1"
desc = "Switch or create tab 2"

# https://github.com/yazi-rs/plugins

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin toggle-pane min-parent"
desc = "Custom layout"

[[mgr.prepend_keymap]]
on = "M"
run = 'plugin mount'

[[mgr.prepend_keymap]]
on = ["l"]
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin hide-preview"
desc = "Hide or show preview"
