# Add navigation in insert mode

[[completion.prepend_keymap]]
on = ["<C-p>"]
run = "arrow -1"
desc = "Move cursor up"

[[completion.prepend_keymap]]
on = ["<C-n>"]
run = "arrow 1"
desc = "Move cursor down"

# Add fg plugin keymap

[[manager.prepend_keymap]]
on = ["f", "f"]
run = "plugin fg --args='fzf'"
desc = "find file by file name"

[[manager.prepend_keymap]]
on = ["f", "g"]
run = "plugin fg"
desc = "find file by content"

[[manager.prepend_keymap]]
on = ["f", "G"]
run = "plugin fg --args='rg'"
desc = "find file by content using ripgrep"

# Add enter behavior to l key
# https://yazi-rs.github.io/docs/tips#smart-enter-enter-for-directory-open-for-file

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

# Relative Motions
# https://github.com/dedukun/relative-motions.yazi

[[manager.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions --args=1"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions --args=2"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions --args=3"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions --args=4"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions --args=5"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions --args=6"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions --args=7"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions --args=8"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions --args=9"
desc = "Move in relative steps"
